#!/bin/bash
# =========================================================
# NextSSL / Anon-leyline — Clone All Repositories
# Generated automatically from data/repos.json
# Total repos: 269  (138 C + 131 V)
# =========================================================
set -uo pipefail
mkdir -p repos

echo "[INFO] Cloning 138 C Source repositories..."
if [ ! -d "repos/C01_OpenSSL___LibreSSL" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/C01_OpenSSL___LibreSSL/; else echo "SKIP C01 exists"; fi
if [ ! -d "repos/C02_wolfSSL__wolfCrypt_" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfssl repos/C02_wolfSSL__wolfCrypt_/; else echo "SKIP C02 exists"; fi
if [ ! -d "repos/C03_Botan__C__17___C_API_" ]; then git clone --depth 1 https://github.com/randombit/botan repos/C03_Botan__C__17___C_API_/; else echo "SKIP C03 exists"; fi
if [ ! -d "repos/C04_libsodium" ]; then git clone --depth 1 https://github.com/jedisct1/libsodium repos/C04_libsodium/; else echo "SKIP C04 exists"; fi
if [ ! -d "repos/C05_libtomcrypt" ]; then git clone --depth 1 https://github.com/libtom/libtomcrypt repos/C05_libtomcrypt/; else echo "SKIP C05 exists"; fi
if [ ! -d "repos/C06_PQClean" ]; then git clone --depth 1 https://github.com/PQClean/PQClean repos/C06_PQClean/; else echo "SKIP C06 exists"; fi
if [ ! -d "repos/C07_XKCP__Keccak_" ]; then git clone --depth 1 https://github.com/XKCP/XKCP repos/C07_XKCP__Keccak_/; else echo "SKIP C07 exists"; fi
if [ ! -d "repos/C08_BLAKE3__official_C_" ]; then git clone --depth 1 https://github.com/BLAKE3-team/BLAKE3 repos/C08_BLAKE3__official_C_/; else echo "SKIP C08 exists"; fi
if [ ! -d "repos/C09_liboqs__Open_Quantum_Safe_" ]; then git clone --depth 1 https://github.com/open-quantum-safe/liboqs repos/C09_liboqs__Open_Quantum_Safe_/; else echo "SKIP C09 exists"; fi
if [ ! -d "repos/C10_Nettle___GnuTLS" ]; then git clone --depth 1 https://git.lysator.liu.se/nettle/nettle repos/C10_Nettle___GnuTLS/; else echo "SKIP C10 exists"; fi
if [ ! -d "repos/C11_Mbed_TLS" ]; then git clone --depth 1 https://github.com/Mbed-TLS/mbedtls repos/C11_Mbed_TLS/; else echo "SKIP C11 exists"; fi
if [ ! -d "repos/C12_BLAKE2_reference_C" ]; then git clone --depth 1 https://github.com/BLAKE2/BLAKE2 repos/C12_BLAKE2_reference_C/; else echo "SKIP C12 exists"; fi
if [ ! -d "repos/C13_XXHash___SipHash___crcany__C_" ]; then git clone --depth 1 https://github.com/Cyan4973/xxHash repos/C13_XXHash___SipHash___crcany__C_/; else echo "SKIP C13 exists"; fi
if [ ! -d "repos/C14_Argon2_reference_C" ]; then git clone --depth 1 https://github.com/P-H-C/phc-winner-argon2 repos/C14_Argon2_reference_C/; else echo "SKIP C14 exists"; fi
if [ ! -d "repos/C15_SUPERCOP___ECRYPT_stream_ciphers__C_asm_" ]; then git clone --depth 1 https://bench.cr.yp.to/supercop.html repos/C15_SUPERCOP___ECRYPT_stream_ciphers__C_asm_/; else echo "SKIP C15 exists"; fi
if [ ! -d "repos/C16_noise-c___libhydrogen__C_" ]; then git clone --depth 1 https://github.com/rweather/noise-c repos/C16_noise-c___libhydrogen__C_/; else echo "SKIP C16 exists"; fi
if [ ! -d "repos/C17_Bouncy_Castle__C____Java___portable____SM_crypto_libs" ]; then git clone --depth 1 https://github.com/bcgit/bc-csharp repos/C17_Bouncy_Castle__C____Java___portable____SM_crypto_libs/; else echo "SKIP C17 exists"; fi
if [ ! -d "repos/C18_Intel_IPP-Crypto___Arm_CE__assembly_" ]; then git clone --depth 1 https://github.com/intel/ipp-crypto repos/C18_Intel_IPP-Crypto___Arm_CE__assembly_/; else echo "SKIP C18 exists"; fi
if [ ! -d "repos/C19_libaegis__aegis-aead_" ]; then git clone --depth 1 https://github.com/aegis-aead/libaegis repos/C19_libaegis__aegis-aead_/; else echo "SKIP C19 exists"; fi
if [ ! -d "repos/C20_rweather_lwc-finalists" ]; then git clone --depth 1 https://github.com/rweather/lwc-finalists repos/C20_rweather_lwc-finalists/; else echo "SKIP C20 exists"; fi
if [ ! -d "repos/C21_bitcoin_libbase58" ]; then git clone --depth 1 https://github.com/bitcoin/libbase58 repos/C21_bitcoin_libbase58/; else echo "SKIP C21 exists"; fi
if [ ! -d "repos/C22_sipa_bech32__C___ref_" ]; then git clone --depth 1 https://github.com/sipa/bech32 repos/C22_sipa_bech32__C___ref_/; else echo "SKIP C22 exists"; fi
if [ ! -d "repos/C23_bancaditalia_secp256k1-frost" ]; then git clone --depth 1 https://github.com/bancaditalia/secp256k1-frost repos/C23_bancaditalia_secp256k1-frost/; else echo "SKIP C23 exists"; fi
if [ ! -d "repos/C24_Taraxa-project_taraxa-vdf" ]; then git clone --depth 1 https://github.com/Taraxa-project/taraxa-vdf repos/C24_Taraxa-project_taraxa-vdf/; else echo "SKIP C24 exists"; fi
if [ ! -d "repos/C25_openfheorg_openfhe-development" ]; then git clone --depth 1 https://github.com/openfheorg/openfhe-development repos/C25_openfheorg_openfhe-development/; else echo "SKIP C25 exists"; fi
if [ ! -d "repos/C26_bitcoin-core_secp256k1" ]; then git clone --depth 1 https://github.com/bitcoin-core/secp256k1 repos/C26_bitcoin-core_secp256k1/; else echo "SKIP C26 exists"; fi
if [ ! -d "repos/C27_openluopworld_block-ciphers" ]; then git clone --depth 1 https://github.com/openluopworld/block-ciphers repos/C27_openluopworld_block-ciphers/; else echo "SKIP C27 exists"; fi
if [ ! -d "repos/C28_floodyberry_supercop__Deoxys-II_ref_" ]; then git clone --depth 1 https://github.com/floodyberry/supercop repos/C28_floodyberry_supercop__Deoxys-II_ref_/; else echo "SKIP C28 exists"; fi
if [ ! -d "repos/C29_CAESAR_Competition_Archive" ]; then git clone --depth 1 https://github.com/floodyberry/supercop repos/C29_CAESAR_Competition_Archive/; else echo "SKIP C29 exists"; fi
if [ ! -d "repos/C30_NIST_LWC_Finalists__ASCON_" ]; then git clone --depth 1 https://github.com/ascon/ascon-c repos/C30_NIST_LWC_Finalists__ASCON_/; else echo "SKIP C30 exists"; fi
if [ ! -d "repos/C31_SUPERCOP___ECRYPT" ]; then git clone --depth 1 https://github.com/floodyberry/supercop repos/C31_SUPERCOP___ECRYPT/; else echo "SKIP C31 exists"; fi
if [ ! -d "repos/C32_Monocypher" ]; then git clone --depth 1 https://github.com/LoupVaillant/Monocypher repos/C32_Monocypher/; else echo "SKIP C32 exists"; fi
if [ ! -d "repos/C33_TinyCrypt" ]; then git clone --depth 1 https://github.com/intel/tinycrypt repos/C33_TinyCrypt/; else echo "SKIP C33 exists"; fi
if [ ! -d "repos/C34_HACL___Verified_C_" ]; then git clone --depth 1 https://github.com/project-everest/hacl-star repos/C34_HACL___Verified_C_/; else echo "SKIP C34 exists"; fi
if [ ! -d "repos/C35_BearSSL" ]; then git clone --depth 1 https://www.bearssl.org/gitweb/?p=BearSSL;a=summary repos/C35_BearSSL/; else echo "SKIP C35 exists"; fi
if [ ! -d "repos/C36_BoringSSL" ]; then git clone --depth 1 https://github.com/google/boringssl repos/C36_BoringSSL/; else echo "SKIP C36 exists"; fi
if [ ! -d "repos/C37_AWS-LC" ]; then git clone --depth 1 https://github.com/aws/aws-lc repos/C37_AWS-LC/; else echo "SKIP C37 exists"; fi
if [ ! -d "repos/C38_libhydrogen" ]; then git clone --depth 1 https://github.com/jedisct1/libhydrogen repos/C38_libhydrogen/; else echo "SKIP C38 exists"; fi
if [ ! -d "repos/C39_libecc" ]; then git clone --depth 1 https://github.com/anssi-fr/libecc repos/C39_libecc/; else echo "SKIP C39 exists"; fi
if [ ! -d "repos/C40_Milagro_Crypto__AMCL_" ]; then git clone --depth 1 https://github.com/apache/incubator-milagro-crypto-c repos/C40_Milagro_Crypto__AMCL_/; else echo "SKIP C40 exists"; fi
if [ ! -d "repos/C41_Relic_Toolkit" ]; then git clone --depth 1 https://github.com/relic-toolkit/relic repos/C41_Relic_Toolkit/; else echo "SKIP C41 exists"; fi
if [ ! -d "repos/C42_libOTe" ]; then git clone --depth 1 https://github.com/osu-crypto/libOTe repos/C42_libOTe/; else echo "SKIP C42 exists"; fi
if [ ! -d "repos/C43_MP-SPDZ" ]; then git clone --depth 1 https://github.com/data61/MP-SPDZ repos/C43_MP-SPDZ/; else echo "SKIP C43 exists"; fi
if [ ! -d "repos/C44_SCALE-MAMBA" ]; then git clone --depth 1 https://github.com/KULeuven-COSIC/SCALE-MAMBA repos/C44_SCALE-MAMBA/; else echo "SKIP C44 exists"; fi
if [ ! -d "repos/C45_NIST_Randomness_Beacon" ]; then git clone --depth 1 https://beacon.nist.gov repos/C45_NIST_Randomness_Beacon/; else echo "SKIP C45 exists"; fi
if [ ! -d "repos/C46_Jitter_Entropy" ]; then git clone --depth 1 https://github.com/smuellerDD/jitterentropy-library repos/C46_Jitter_Entropy/; else echo "SKIP C46 exists"; fi
if [ ! -d "repos/C47_Intel_IPP_FIPS" ]; then git clone --depth 1 https://github.com/intel/cryptography-primitives repos/C47_Intel_IPP_FIPS/; else echo "SKIP C47 exists"; fi
if [ ! -d "repos/C48_Intel_linux-sgx" ]; then git clone --depth 1 https://github.com/intel/linux-sgx repos/C48_Intel_linux-sgx/; else echo "SKIP C48 exists"; fi
if [ ! -d "repos/C49_AMD_SEV" ]; then git clone --depth 1 https://github.com/AMDESE/AMDSEV repos/C49_AMD_SEV/; else echo "SKIP C49 exists"; fi
if [ ! -d "repos/C50_AMD_SEV_Tool" ]; then git clone --depth 1 https://github.com/AMDESE/sev-tool repos/C50_AMD_SEV_Tool/; else echo "SKIP C50 exists"; fi
if [ ! -d "repos/C51_ARM_Trusted_Firmware" ]; then git clone --depth 1 https://github.com/ARM-software/arm-trusted-firmware repos/C51_ARM_Trusted_Firmware/; else echo "SKIP C51 exists"; fi
if [ ! -d "repos/C52_TPM2-TSS" ]; then git clone --depth 1 https://github.com/tpm2-software/tpm2-tss repos/C52_TPM2-TSS/; else echo "SKIP C52 exists"; fi
if [ ! -d "repos/C53_OpenSC" ]; then git clone --depth 1 https://github.com/OpenSC/OpenSC repos/C53_OpenSC/; else echo "SKIP C53 exists"; fi
if [ ! -d "repos/C54_p11-kit" ]; then git clone --depth 1 https://github.com/p11-glue/p11-kit repos/C54_p11-kit/; else echo "SKIP C54 exists"; fi
if [ ! -d "repos/C55_Open_Enclave_SDK" ]; then git clone --depth 1 https://github.com/openenclave/openenclave repos/C55_Open_Enclave_SDK/; else echo "SKIP C55 exists"; fi
if [ ! -d "repos/C56_Gramine" ]; then git clone --depth 1 https://github.com/gramineproject/gramine repos/C56_Gramine/; else echo "SKIP C56 exists"; fi
if [ ! -d "repos/C57_AWS_Nitro_Enclaves_CLI" ]; then git clone --depth 1 https://github.com/aws/aws-nitro-enclaves-cli repos/C57_AWS_Nitro_Enclaves_CLI/; else echo "SKIP C57 exists"; fi
if [ ! -d "repos/C58_NVIDIA_Confidential_Computing" ]; then git clone --depth 1 https://github.com/NVIDIA/nvtrust repos/C58_NVIDIA_Confidential_Computing/; else echo "SKIP C58 exists"; fi
if [ ! -d "repos/C59_OpenJDK" ]; then git clone --depth 1 https://github.com/openjdk/jdk repos/C59_OpenJDK/; else echo "SKIP C59 exists"; fi
if [ ! -d "repos/C60_RNG_Tools" ]; then git clone --depth 1 https://github.com/nhorman/rng-tools repos/C60_RNG_Tools/; else echo "SKIP C60 exists"; fi
if [ ! -d "repos/C61_Haveged" ]; then git clone --depth 1 https://github.com/jirka-h/haveged repos/C61_Haveged/; else echo "SKIP C61 exists"; fi
if [ ! -d "repos/C62_Jitter_Entropy_Library" ]; then git clone --depth 1 https://github.com/smuellerDD/jitterentropy-library repos/C62_Jitter_Entropy_Library/; else echo "SKIP C62 exists"; fi
if [ ! -d "repos/C63_Romulus_AEAD" ]; then git clone --depth 1 https://github.com/romulusae/romulus repos/C63_Romulus_AEAD/; else echo "SKIP C63 exists"; fi
if [ ! -d "repos/C64_TinyJAMBU" ]; then git clone --depth 1 https://github.com/rweather/TinyJAMBU repos/C64_TinyJAMBU/; else echo "SKIP C64 exists"; fi
if [ ! -d "repos/C65_TinyJAMBU__alt_" ]; then git clone --depth 1 https://github.com/itzmeanjan/tinyjambu repos/C65_TinyJAMBU__alt_/; else echo "SKIP C65 exists"; fi
if [ ! -d "repos/C66_SUPERCOP_Benchmark_Suite" ]; then git clone --depth 1 https://github.com/floodyberry/supercop repos/C66_SUPERCOP_Benchmark_Suite/; else echo "SKIP C66 exists"; fi
if [ ! -d "repos/C67_ZKInterface" ]; then git clone --depth 1 https://github.com/ZKInterface/ZKInterface repos/C67_ZKInterface/; else echo "SKIP C67 exists"; fi
if [ ! -d "repos/C68_NIST_Randomness_Beacon" ]; then git clone --depth 1 https://beacon.nist.gov repos/C68_NIST_Randomness_Beacon/; else echo "SKIP C68 exists"; fi
if [ ! -d "repos/C69_Open_Quantum_Safe_provider" ]; then git clone --depth 1 https://github.com/open-quantum-safe/oqs-provider repos/C69_Open_Quantum_Safe_provider/; else echo "SKIP C69 exists"; fi
if [ ! -d "repos/C70_EMP_Toolkit" ]; then git clone --depth 1 https://github.com/emp-toolkit/emp-tool repos/C70_EMP_Toolkit/; else echo "SKIP C70 exists"; fi
if [ ! -d "repos/C71_Zama_Concrete" ]; then git clone --depth 1 https://github.com/zama-ai/concrete repos/C71_Zama_Concrete/; else echo "SKIP C71 exists"; fi
if [ ! -d "repos/C72_Zama_TFHE-rs" ]; then git clone --depth 1 https://github.com/zama-ai/tfhe-rs repos/C72_Zama_TFHE-rs/; else echo "SKIP C72 exists"; fi
if [ ! -d "repos/C73_Meta_CrypTen" ]; then git clone --depth 1 https://github.com/facebookresearch/CrypTen repos/C73_Meta_CrypTen/; else echo "SKIP C73 exists"; fi
if [ ! -d "repos/C74_Ascon_official_C" ]; then git clone --depth 1 https://github.com/ascon/ascon-c repos/C74_Ascon_official_C/; else echo "SKIP C74 exists"; fi
if [ ! -d "repos/C75_LWC_Finalists" ]; then git clone --depth 1 https://github.com/rweather/lwc-finalists repos/C75_LWC_Finalists/; else echo "SKIP C75 exists"; fi
if [ ! -d "repos/C76_Intel_IPP_FIPS" ]; then git clone --depth 1 https://github.com/intel/cryptography-primitives repos/C76_Intel_IPP_FIPS/; else echo "SKIP C76 exists"; fi
if [ ! -d "repos/C77_Intel_IPP_Crypto" ]; then git clone --depth 1 https://github.com/intel/ipp-crypto repos/C77_Intel_IPP_Crypto/; else echo "SKIP C77 exists"; fi
if [ ! -d "repos/C78_libopenbsd" ]; then git clone --depth 1 https://github.com/openbsd/src repos/C78_libopenbsd/; else echo "SKIP C78 exists"; fi
if [ ! -d "repos/C79_wolfSSL_JNI_FIPS" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfcrypt-jni repos/C79_wolfSSL_JNI_FIPS/; else echo "SKIP C79 exists"; fi
if [ ! -d "repos/C80_Botan_PKCS_11" ]; then git clone --depth 1 https://github.com/randombit/botan/tree/master/src/lib/prov/pkcs11 repos/C80_Botan_PKCS_11/; else echo "SKIP C80 exists"; fi
if [ ! -d "repos/C81_OpenSC_libp11" ]; then git clone --depth 1 https://github.com/OpenSC/libp11 repos/C81_OpenSC_libp11/; else echo "SKIP C81 exists"; fi
if [ ! -d "repos/C82_NIST_Entropy_Assessment" ]; then git clone --depth 1 https://github.com/usnistgov/SP800-90B_EntropyAssessment repos/C82_NIST_Entropy_Assessment/; else echo "SKIP C82 exists"; fi
if [ ! -d "repos/C83_NIST_Randomness_Beacon_client" ]; then git clone --depth 1 https://github.com/usnistgov/RandomnessBeacon repos/C83_NIST_Randomness_Beacon_client/; else echo "SKIP C83 exists"; fi
if [ ! -d "repos/C84_VRF__DJB_ref_" ]; then git clone --depth 1 https://github.com/jedisct1/vrf repos/C84_VRF__DJB_ref_/; else echo "SKIP C84 exists"; fi
if [ ! -d "repos/C85_Threshold_ECDSA_by_ZenGo" ]; then git clone --depth 1 https://github.com/ZenGo-X/multi-party-ecdsa repos/C85_Threshold_ECDSA_by_ZenGo/; else echo "SKIP C85 exists"; fi
if [ ! -d "repos/C86_TSS-lib__Binance_" ]; then git clone --depth 1 https://github.com/bnb-chain/tss-lib repos/C86_TSS-lib__Binance_/; else echo "SKIP C86 exists"; fi
if [ ! -d "repos/C87_ALICE_threshold_signatures" ]; then git clone --depth 1 https://github.com/getamis/alice repos/C87_ALICE_threshold_signatures/; else echo "SKIP C87 exists"; fi
if [ ! -d "repos/C88_ING_Threshold_Signatures" ]; then git clone --depth 1 https://github.com/ing-bank/threshold-signatures repos/C88_ING_Threshold_Signatures/; else echo "SKIP C88 exists"; fi
if [ ! -d "repos/C89_OpenSSL_Engines" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/C89_OpenSSL_Engines/; else echo "SKIP C89 exists"; fi
if [ ! -d "repos/C90_Microsoft_BCrypt_primitives" ]; then git clone --depth 1 https://github.com/microsoft repos/C90_Microsoft_BCrypt_primitives/; else echo "SKIP C90 exists"; fi
if [ ! -d "repos/C91_NIST_SP800-90C_samples" ]; then git clone --depth 1 https://github.com/usnistgov/SP800-90B_EntropyAssessment repos/C91_NIST_SP800-90C_samples/; else echo "SKIP C91 exists"; fi
if [ ! -d "repos/C92_NIST_SP800-90B_tool" ]; then git clone --depth 1 https://github.com/usnistgov/SP800-90B_EntropyAssessment repos/C92_NIST_SP800-90B_tool/; else echo "SKIP C92 exists"; fi
if [ ! -d "repos/C93_SPHINCS__reference" ]; then git clone --depth 1 https://github.com/sphincs/sphincsplus repos/C93_SPHINCS__reference/; else echo "SKIP C93 exists"; fi
if [ ! -d "repos/C94_Classic_McEliece" ]; then git clone --depth 1 https://github.com/pqclean/pqclean repos/C94_Classic_McEliece/; else echo "SKIP C94 exists"; fi
if [ ! -d "repos/C95_Kyber_reference" ]; then git clone --depth 1 https://github.com/pq-crystals/kyber repos/C95_Kyber_reference/; else echo "SKIP C95 exists"; fi
if [ ! -d "repos/C96_Dilithium_reference" ]; then git clone --depth 1 https://github.com/pq-crystals/dilithium repos/C96_Dilithium_reference/; else echo "SKIP C96 exists"; fi
if [ ! -d "repos/C97_Falcon_reference" ]; then git clone --depth 1 https://github.com/pq-crystals/falcon repos/C97_Falcon_reference/; else echo "SKIP C97 exists"; fi
if [ ! -d "repos/C98_NTRU_Prime" ]; then git clone --depth 1 https://github.com/ntruprime/ntruprime repos/C98_NTRU_Prime/; else echo "SKIP C98 exists"; fi
if [ ! -d "repos/C99_ML-KEM___Kyber_NIST" ]; then git clone --depth 1 https://github.com/pq-crystals/kyber repos/C99_ML-KEM___Kyber_NIST/; else echo "SKIP C99 exists"; fi
if [ ! -d "repos/C99_opencryptoki" ]; then git clone --depth 1 https://github.com/opencryptoki/opencryptoki repos/C99_opencryptoki/; else echo "SKIP C99 exists"; fi
if [ ! -d "repos/C100_Linux_kernel__dev_random" ]; then git clone --depth 1 https://github.com/torvalds/linux repos/C100_Linux_kernel__dev_random/; else echo "SKIP C100 exists"; fi
if [ ! -d "repos/C101_Windows_CNG" ]; then git clone --depth 1 https://docs.microsoft.com/windows/win32/seccng/cng-portal repos/C101_Windows_CNG/; else echo "SKIP C101 exists"; fi
if [ ! -d "repos/C102_ChaCha20__dev_random" ]; then git clone --depth 1 https://github.com/torvalds/linux repos/C102_ChaCha20__dev_random/; else echo "SKIP C102 exists"; fi
if [ ! -d "repos/C103_Cloudflare_Go_VRF" ]; then git clone --depth 1 https://github.com/cloudflare/go-vrf repos/C103_Cloudflare_Go_VRF/; else echo "SKIP C103 exists"; fi
if [ ! -d "repos/C104_Crypto____Wei_Dai_" ]; then git clone --depth 1 https://github.com/weidai11/cryptopp repos/C104_Crypto____Wei_Dai_/; else echo "SKIP C104 exists"; fi
if [ ! -d "repos/C105_eSTREAM_Reference" ]; then git clone --depth 1 http://www.ecrypt.eu.org/stream/ repos/C105_eSTREAM_Reference/; else echo "SKIP C105 exists"; fi
if [ ! -d "repos/C106_Botan_X.509_PKI" ]; then git clone --depth 1 https://github.com/randombit/botan repos/C106_Botan_X.509_PKI/; else echo "SKIP C106 exists"; fi
if [ ! -d "repos/C107_OpenSSL_PKI" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/C107_OpenSSL_PKI/; else echo "SKIP C107 exists"; fi
if [ ! -d "repos/C108_wolfSSL_PKI" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfssl repos/C108_wolfSSL_PKI/; else echo "SKIP C108 exists"; fi
if [ ! -d "repos/C109_GnuTLS_PKI" ]; then git clone --depth 1 https://gitlab.com/gnutls/gnutls repos/C109_GnuTLS_PKI/; else echo "SKIP C109 exists"; fi
if [ ! -d "repos/C110_CFSSL__Cloudflare_" ]; then git clone --depth 1 https://github.com/cloudflare/cfssl repos/C110_CFSSL__Cloudflare_/; else echo "SKIP C110 exists"; fi
if [ ! -d "repos/C111_cert-manager__K8s_" ]; then git clone --depth 1 https://github.com/cert-manager/cert-manager repos/C111_cert-manager__K8s_/; else echo "SKIP C111 exists"; fi
if [ ! -d "repos/C112_libsnark__SCIPR_Lab_" ]; then git clone --depth 1 https://github.com/scipr-lab/libsnark repos/C112_libsnark__SCIPR_Lab_/; else echo "SKIP C112 exists"; fi
if [ ! -d "repos/C113_bellman__Zcash_" ]; then git clone --depth 1 https://github.com/zkcrypto/bellman repos/C113_bellman__Zcash_/; else echo "SKIP C113 exists"; fi
if [ ! -d "repos/C114_arkworks__zkSNARK_ecosystem_" ]; then git clone --depth 1 https://github.com/arkworks-rs repos/C114_arkworks__zkSNARK_ecosystem_/; else echo "SKIP C114 exists"; fi
if [ ! -d "repos/C115_SECP256K1_zk" ]; then git clone --depth 1 https://github.com/bitcoin-core/secp256k1 repos/C115_SECP256K1_zk/; else echo "SKIP C115 exists"; fi
if [ ! -d "repos/C116_MIRACL_Core" ]; then git clone --depth 1 https://github.com/miracl/core repos/C116_MIRACL_Core/; else echo "SKIP C116 exists"; fi
if [ ! -d "repos/C117_RELIC__pairing-based_" ]; then git clone --depth 1 https://github.com/relic-toolkit/relic repos/C117_RELIC__pairing-based_/; else echo "SKIP C117 exists"; fi
if [ ! -d "repos/C118_OpenBSD_libc_crypto" ]; then git clone --depth 1 https://github.com/openbsd/src repos/C118_OpenBSD_libc_crypto/; else echo "SKIP C118 exists"; fi
if [ ! -d "repos/C119_libsodium_stream" ]; then git clone --depth 1 https://github.com/jedisct1/libsodium repos/C119_libsodium_stream/; else echo "SKIP C119 exists"; fi
if [ ! -d "repos/C120_Monocypher__all-in-one_" ]; then git clone --depth 1 https://github.com/LoupVaillant/Monocypher repos/C120_Monocypher__all-in-one_/; else echo "SKIP C120 exists"; fi
if [ ! -d "repos/C121_TinyCrypt__Intel_" ]; then git clone --depth 1 https://github.com/intel/tinycrypt repos/C121_TinyCrypt__Intel_/; else echo "SKIP C121 exists"; fi
if [ ! -d "repos/C122_Mbed_TLS_AEAD_MAC" ]; then git clone --depth 1 https://github.com/Mbed-TLS/mbedtls repos/C122_Mbed_TLS_AEAD_MAC/; else echo "SKIP C122 exists"; fi
if [ ! -d "repos/C123_libhydrogen" ]; then git clone --depth 1 https://github.com/jedisct1/libhydrogen repos/C123_libhydrogen/; else echo "SKIP C123 exists"; fi
if [ ! -d "repos/C124_BearSSL_primitives" ]; then git clone --depth 1 https://bearssl.org repos/C124_BearSSL_primitives/; else echo "SKIP C124 exists"; fi
if [ ! -d "repos/C125_BoringSSL_primitives" ]; then git clone --depth 1 https://github.com/google/boringssl repos/C125_BoringSSL_primitives/; else echo "SKIP C125 exists"; fi
if [ ! -d "repos/C126_AWS-LC_crypto" ]; then git clone --depth 1 https://github.com/aws/aws-lc repos/C126_AWS-LC_crypto/; else echo "SKIP C126 exists"; fi
if [ ! -d "repos/C127_OpenSSL_EVP" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/C127_OpenSSL_EVP/; else echo "SKIP C127 exists"; fi
if [ ! -d "repos/C128_PQClean__all_PQC_" ]; then git clone --depth 1 https://github.com/PQClean/PQClean repos/C128_PQClean__all_PQC_/; else echo "SKIP C128 exists"; fi
if [ ! -d "repos/C129_SPHINCS__reference" ]; then git clone --depth 1 https://github.com/sphincs/sphincsplus repos/C129_SPHINCS__reference/; else echo "SKIP C129 exists"; fi
if [ ! -d "repos/C130_NTRU_Prime" ]; then git clone --depth 1 https://github.com/ntruprime/ntruprime repos/C130_NTRU_Prime/; else echo "SKIP C130 exists"; fi
if [ ! -d "repos/C131_Classic_McEliece" ]; then git clone --depth 1 https://github.com/PQClean/PQClean repos/C131_Classic_McEliece/; else echo "SKIP C131 exists"; fi
if [ ! -d "repos/C132_Kyber_ML-KEM" ]; then git clone --depth 1 https://github.com/pq-crystals/kyber repos/C132_Kyber_ML-KEM/; else echo "SKIP C132 exists"; fi
if [ ! -d "repos/C133_Dilithium_ML-DSA" ]; then git clone --depth 1 https://github.com/pq-crystals/dilithium repos/C133_Dilithium_ML-DSA/; else echo "SKIP C133 exists"; fi
if [ ! -d "repos/C134_Falcon" ]; then git clone --depth 1 https://github.com/pq-crystals/falcon repos/C134_Falcon/; else echo "SKIP C134 exists"; fi
if [ ! -d "repos/C135_Signal_Protocol_libsignal" ]; then git clone --depth 1 https://github.com/signalapp/libsignal repos/C135_Signal_Protocol_libsignal/; else echo "SKIP C135 exists"; fi
if [ ! -d "repos/C136_OpenSSH" ]; then git clone --depth 1 https://github.com/openssh/openssh-portable repos/C136_OpenSSH/; else echo "SKIP C136 exists"; fi
if [ ! -d "repos/C137_OpenSSH_crypto" ]; then git clone --depth 1 https://github.com/openssh/openssh-portable repos/C137_OpenSSH_crypto/; else echo "SKIP C137 exists"; fi

echo "[INFO] Cloning 131 Verification/KAT repositories..."
if [ ! -d "repos/V01_NIST_ACVP___CAVS_Test_Vectors" ]; then git clone --depth 1 https://github.com/usnistgov/ACVP repos/V01_NIST_ACVP___CAVS_Test_Vectors/; else echo "SKIP V01 exists"; fi
if [ ! -d "repos/V02_cryptography__PyCA_" ]; then git clone --depth 1 https://cryptography.io repos/V02_cryptography__PyCA_/; else echo "SKIP V02 exists"; fi
if [ ! -d "repos/V03_PyCryptodome" ]; then git clone --depth 1 https://pycryptodome.readthedocs.io repos/V03_PyCryptodome/; else echo "SKIP V03 exists"; fi
if [ ! -d "repos/V04_passlib___pyca_bcrypt" ]; then git clone --depth 1 https://passlib.readthedocs.io repos/V04_passlib___pyca_bcrypt/; else echo "SKIP V04 exists"; fi
if [ ! -d "repos/V05_PyNaCl___pynacl__libsodium_Python_" ]; then git clone --depth 1 https://github.com/pyca/pynacl repos/V05_PyNaCl___pynacl__libsodium_Python_/; else echo "SKIP V05 exists"; fi
if [ ! -d "repos/V06_liboqs-python__pyoqs_" ]; then git clone --depth 1 https://github.com/open-quantum-safe/liboqs-python repos/V06_liboqs-python__pyoqs_/; else echo "SKIP V06 exists"; fi
if [ ! -d "repos/V07_Python_hashlib___hmac___secrets__stdlib_" ]; then git clone --depth 1 https://docs.python.org/3/library/hashlib.html repos/V07_Python_hashlib___hmac___secrets__stdlib_/; else echo "SKIP V07 exists"; fi
if [ ! -d "repos/V08_py_ecc___coincurve___fastecdsa" ]; then git clone --depth 1 https://github.com/ethereum/py_ecc repos/V08_py_ecc___coincurve___fastecdsa/; else echo "SKIP V08 exists"; fi
if [ ! -d "repos/V09_SageMath___galois___sympy" ]; then git clone --depth 1 https://www.sagemath.org repos/V09_SageMath___galois___sympy/; else echo "SKIP V09 exists"; fi
if [ ! -d "repos/V10_pysha3___xxhash___crcmod___zlib__Python_" ]; then git clone --depth 1 https://pypi.org/project/xxhash/ repos/V10_pysha3___xxhash___crcmod___zlib__Python_/; else echo "SKIP V10 exists"; fi
if [ ! -d "repos/V11_Wycheproof__Google_" ]; then git clone --depth 1 https://github.com/google/wycheproof repos/V11_Wycheproof__Google_/; else echo "SKIP V11 exists"; fi
if [ ! -d "repos/V12_NIST_PQC_Official_KAT_Vectors" ]; then git clone --depth 1 https://csrc.nist.gov/projects/post-quantum-cryptography repos/V12_NIST_PQC_Official_KAT_Vectors/; else echo "SKIP V12 exists"; fi
if [ ! -d "repos/V13_Tink__Python____pyseto___joserfc___Noise_protocol_refs" ]; then git clone --depth 1 https://github.com/tink-crypto/tink-py repos/V13_Tink__Python____pyseto___joserfc___Noise_protocol_refs/; else echo "SKIP V13 exists"; fi
if [ ! -d "repos/V14_py-snark___arkworks-py___py_ecc_ZK___starkware-crypto" ]; then git clone --depth 1 https://github.com/starkware-libs/starkware-crypto-utils repos/V14_py-snark___arkworks-py___py_ecc_ZK___starkware-crypto/; else echo "SKIP V14 exists"; fi
if [ ! -d "repos/V15_asn1crypto___pyOpenSSL___certvalidator___cryptography_X.509" ]; then git clone --depth 1 https://github.com/wbond/asn1crypto repos/V15_asn1crypto___pyOpenSSL___certvalidator___cryptography_X.509/; else echo "SKIP V15 exists"; fi
if [ ! -d "repos/V16_python-base58__keis_base58_" ]; then git clone --depth 1 https://github.com/keis/base58 repos/V16_python-base58__keis_base58_/; else echo "SKIP V16 exists"; fi
if [ ! -d "repos/V17_openfhe-python" ]; then git clone --depth 1 https://github.com/openfheorg/openfhe-python repos/V17_openfhe-python/; else echo "SKIP V17 exists"; fi
if [ ! -d "repos/V18_ingonyama-zk_poseidon-hash" ]; then git clone --depth 1 https://github.com/ingonyama-zk/poseidon-hash repos/V18_ingonyama-zk_poseidon-hash/; else echo "SKIP V18 exists"; fi
if [ ! -d "repos/V19_CRYPTOLEN__KAT_vectors_" ]; then git clone --depth 1 https://github.com/usnistgov/ACVP-Server repos/V19_CRYPTOLEN__KAT_vectors_/; else echo "SKIP V19 exists"; fi
if [ ! -d "repos/V20_SUPERCOP_benchmarks" ]; then git clone --depth 1 https://bench.cr.yp.to/supercop.html repos/V20_SUPERCOP_benchmarks/; else echo "SKIP V20 exists"; fi
if [ ! -d "repos/V21_NIST_CAVP_Test_Vectors" ]; then git clone --depth 1 https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program repos/V21_NIST_CAVP_Test_Vectors/; else echo "SKIP V21 exists"; fi
if [ ! -d "repos/V22_CAESAR_Competition_KATs" ]; then git clone --depth 1 https:// competitions.cr.yp.to/caesar-submissions.html repos/V22_CAESAR_Competition_KATs/; else echo "SKIP V22 exists"; fi
if [ ! -d "repos/V23_NIST_PQC_KAT_Archive" ]; then git clone --depth 1 https://csrc.nist.gov/Projects/post-quantum-cryptography/post-quantum-cryptography-standardization/round-4-submissions repos/V23_NIST_PQC_KAT_Archive/; else echo "SKIP V23 exists"; fi
if [ ! -d "repos/V24_Wycheproof" ]; then git clone --depth 1 https://github.com/google/wycheproof repos/V24_Wycheproof/; else echo "SKIP V24 exists"; fi
if [ ! -d "repos/V25_Project_Wycheproof__Java_" ]; then git clone --depth 1 https://github.com/google/wycheproof repos/V25_Project_Wycheproof__Java_/; else echo "SKIP V25 exists"; fi
if [ ! -d "repos/V26_Cryptofuzz" ]; then git clone --depth 1 https://github.com/guidovranken/cryptofuzz repos/V26_Cryptofuzz/; else echo "SKIP V26 exists"; fi
if [ ! -d "repos/V27_BoringSSL_Test_Suite" ]; then git clone --depth 1 https://github.com/google/boringssl/tree/master/ssl/test repos/V27_BoringSSL_Test_Suite/; else echo "SKIP V27 exists"; fi
if [ ! -d "repos/V28_OpenSSL_Test_Suite" ]; then git clone --depth 1 https://github.com/openssl/openssl/tree/master/test repos/V28_OpenSSL_Test_Suite/; else echo "SKIP V28 exists"; fi
if [ ! -d "repos/V29_libsodium_Test_Vectors" ]; then git clone --depth 1 https://github.com/jedisct1/libsodium/tree/master/test/default repos/V29_libsodium_Test_Vectors/; else echo "SKIP V29 exists"; fi
if [ ! -d "repos/V30_PQClean_Test_Framework" ]; then git clone --depth 1 https://github.com/PQClean/PQClean/tree/master/test repos/V30_PQClean_Test_Framework/; else echo "SKIP V30 exists"; fi
if [ ! -d "repos/V31_Botan_Test_Data" ]; then git clone --depth 1 https://github.com/randombit/botan/tree/master/src/tests/data repos/V31_Botan_Test_Data/; else echo "SKIP V31 exists"; fi
if [ ! -d "repos/V32_NIST_STS__Statistical_Test_Suite_" ]; then git clone --depth 1 https://csrc.nist.gov/projects/random-bit-generation/documentation-and-software repos/V32_NIST_STS__Statistical_Test_Suite_/; else echo "SKIP V32 exists"; fi
if [ ! -d "repos/V33_Entropy_Assessment_Tool__SP800-90B_" ]; then git clone --depth 1 https://github.com/usnistgov/SP800-90B_EntropyAssessment repos/V33_Entropy_Assessment_Tool__SP800-90B_/; else echo "SKIP V33 exists"; fi
if [ ! -d "repos/V34_Dieharder" ]; then git clone --depth 1 https://github.com/seehuhn/dieharder repos/V34_Dieharder/; else echo "SKIP V34 exists"; fi
if [ ! -d "repos/V35_PractRand" ]; then git clone --depth 1 https://pracrand.sourceforge.net repos/V35_PractRand/; else echo "SKIP V35 exists"; fi
if [ ! -d "repos/V36_TestU01__L_Ecuyer_" ]; then git clone --depth 1 http://simul.iro.umontreal.ca/testu01/tu01.html repos/V36_TestU01__L_Ecuyer_/; else echo "SKIP V36 exists"; fi
if [ ! -d "repos/V37_MP-SPDZ_Test_Suite" ]; then git clone --depth 1 https://github.com/data61/MP-SPDZ/tree/master/Protocols repos/V37_MP-SPDZ_Test_Suite/; else echo "SKIP V37 exists"; fi
if [ ! -d "repos/V38_SCALE-MAMBA_Test_Cases" ]; then git clone --depth 1 https://github.com/KULeuven-COSIC/SCALE-MAMBA/tree/master/Programs repos/V38_SCALE-MAMBA_Test_Cases/; else echo "SKIP V38 exists"; fi
if [ ! -d "repos/V39_RELIC_Test_Suite" ]; then git clone --depth 1 https://github.com/relic-toolkit/relic/tree/master/test repos/V39_RELIC_Test_Suite/; else echo "SKIP V39 exists"; fi
if [ ! -d "repos/V40_Titan_Benchmark" ]; then git clone --depth 1 https://github.com/mjosaarinen/tiny_sha3 repos/V40_Titan_Benchmark/; else echo "SKIP V40 exists"; fi
if [ ! -d "repos/V41_NIST_ACVP-Server" ]; then git clone --depth 1 https://github.com/usnistgov/ACVP-Server repos/V41_NIST_ACVP-Server/; else echo "SKIP V41 exists"; fi
if [ ! -d "repos/V42_Intel_SGX_tests" ]; then git clone --depth 1 https://github.com/intel/linux-sgx repos/V42_Intel_SGX_tests/; else echo "SKIP V42 exists"; fi
if [ ! -d "repos/V43_AMD_SEV_utils" ]; then git clone --depth 1 https://github.com/AMDESE/sev-tool repos/V43_AMD_SEV_utils/; else echo "SKIP V43 exists"; fi
if [ ! -d "repos/V44_TrustZone_Tests" ]; then git clone --depth 1 https://github.com/ARM-software/arm-trusted-firmware repos/V44_TrustZone_Tests/; else echo "SKIP V44 exists"; fi
if [ ! -d "repos/V45_TPM2-TSS_tests" ]; then git clone --depth 1 https://github.com/tpm2-software/tpm2-tss repos/V45_TPM2-TSS_tests/; else echo "SKIP V45 exists"; fi
if [ ! -d "repos/V46_OpenSC_Test_Suite" ]; then git clone --depth 1 https://github.com/OpenSC/OpenSC repos/V46_OpenSC_Test_Suite/; else echo "SKIP V46 exists"; fi
if [ ! -d "repos/V47_p11-kit_tests" ]; then git clone --depth 1 https://github.com/p11-glue/p11-kit repos/V47_p11-kit_tests/; else echo "SKIP V47 exists"; fi
if [ ! -d "repos/V48_Open_Enclave_tests" ]; then git clone --depth 1 https://github.com/openenclave/openenclave repos/V48_Open_Enclave_tests/; else echo "SKIP V48 exists"; fi
if [ ! -d "repos/V49_Gramine_CI_tests" ]; then git clone --depth 1 https://github.com/gramineproject/gramine repos/V49_Gramine_CI_tests/; else echo "SKIP V49 exists"; fi
if [ ! -d "repos/V50_AWS_Nitro_SDK" ]; then git clone --depth 1 https://github.com/aws/aws-nitro-enclaves-sdk-c repos/V50_AWS_Nitro_SDK/; else echo "SKIP V50 exists"; fi
if [ ! -d "repos/V51_NVIDIA_CC_tests" ]; then git clone --depth 1 https://github.com/NVIDIA/nvtrust repos/V51_NVIDIA_CC_tests/; else echo "SKIP V51 exists"; fi
if [ ! -d "repos/V52_OpenJDK_Crypto_tests" ]; then git clone --depth 1 https://github.com/openjdk/jdk repos/V52_OpenJDK_Crypto_tests/; else echo "SKIP V52 exists"; fi
if [ ! -d "repos/V53_wolfSSL_FIPS_test" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfssl repos/V53_wolfSSL_FIPS_test/; else echo "SKIP V53 exists"; fi
if [ ! -d "repos/V54_botan-p11_tests" ]; then git clone --depth 1 https://github.com/randombit/botan repos/V54_botan-p11_tests/; else echo "SKIP V54 exists"; fi
if [ ! -d "repos/V55_libp11_tests" ]; then git clone --depth 1 https://github.com/OpenSC/libp11 repos/V55_libp11_tests/; else echo "SKIP V55 exists"; fi
if [ ! -d "repos/V56_OpenSSL_ENGINE_test" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/V56_OpenSSL_ENGINE_test/; else echo "SKIP V56 exists"; fi
if [ ! -d "repos/V57_Mbed_TLS_tests" ]; then git clone --depth 1 https://github.com/Mbed-TLS/mbedtls repos/V57_Mbed_TLS_tests/; else echo "SKIP V57 exists"; fi
if [ ! -d "repos/V58_Dieharder" ]; then git clone --depth 1 https://github.com/seehuhn/dieharder repos/V58_Dieharder/; else echo "SKIP V58 exists"; fi
if [ ! -d "repos/V59_PractRand" ]; then git clone --depth 1 https://pracrand.sourceforge.net repos/V59_PractRand/; else echo "SKIP V59 exists"; fi
if [ ! -d "repos/V60_TestU01" ]; then git clone --depth 1 http://simul.iro.umontreal.ca/testu01/tu01.html repos/V60_TestU01/; else echo "SKIP V60 exists"; fi
if [ ! -d "repos/V61_NIST_STS" ]; then git clone --depth 1 https://csrc.nist.gov/projects/random-bit-generation/documentation-and-software repos/V61_NIST_STS/; else echo "SKIP V61 exists"; fi
if [ ! -d "repos/V62_SP800-90B_Entropy_Tool" ]; then git clone --depth 1 https://github.com/usnistgov/SP800-90B_EntropyAssessment repos/V62_SP800-90B_Entropy_Tool/; else echo "SKIP V62 exists"; fi
if [ ! -d "repos/V63_NIST_Randomness_Beacon_client" ]; then git clone --depth 1 https://github.com/usnistgov/RandomnessBeacon repos/V63_NIST_Randomness_Beacon_client/; else echo "SKIP V63 exists"; fi
if [ ! -d "repos/V64_VRF_Test_vectors" ]; then git clone --depth 1 https://github.com/jedisct1/vrf repos/V64_VRF_Test_vectors/; else echo "SKIP V64 exists"; fi
if [ ! -d "repos/V65_CNG_test_vectors" ]; then git clone --depth 1 https://docs.microsoft.com/windows/win32/seccng/test-vectors repos/V65_CNG_test_vectors/; else echo "SKIP V65 exists"; fi
if [ ! -d "repos/V66_Java_JCE_test" ]; then git clone --depth 1 https://github.com/openjdk/jdk repos/V66_Java_JCE_test/; else echo "SKIP V66 exists"; fi
if [ ! -d "repos/V67_PQClean_test_framework" ]; then git clone --depth 1 https://github.com/PQClean/PQClean repos/V67_PQClean_test_framework/; else echo "SKIP V67 exists"; fi
if [ ! -d "repos/V68_oqs-provider_tests" ]; then git clone --depth 1 https://github.com/open-quantum-safe/oqs-provider repos/V68_oqs-provider_tests/; else echo "SKIP V68 exists"; fi
if [ ! -d "repos/V69_MP-SPDZ_Test_Suite" ]; then git clone --depth 1 https://github.com/data61/MP-SPDZ repos/V69_MP-SPDZ_Test_Suite/; else echo "SKIP V69 exists"; fi
if [ ! -d "repos/V70_SCALE-MAMBA_Tests" ]; then git clone --depth 1 https://github.com/KULeuven-COSIC/SCALE-MAMBA repos/V70_SCALE-MAMBA_Tests/; else echo "SKIP V70 exists"; fi
if [ ! -d "repos/V71_EMP_Toolkit_tests" ]; then git clone --depth 1 https://github.com/emp-toolkit/emp-tool repos/V71_EMP_Toolkit_tests/; else echo "SKIP V71 exists"; fi
if [ ! -d "repos/V72_Concrete_tests" ]; then git clone --depth 1 https://github.com/zama-ai/concrete repos/V72_Concrete_tests/; else echo "SKIP V72 exists"; fi
if [ ! -d "repos/V73_TFHE-rs_tests" ]; then git clone --depth 1 https://github.com/zama-ai/tfhe-rs repos/V73_TFHE-rs_tests/; else echo "SKIP V73 exists"; fi
if [ ! -d "repos/V74_CrypTen_tests" ]; then git clone --depth 1 https://github.com/facebookresearch/CrypTen repos/V74_CrypTen_tests/; else echo "SKIP V74 exists"; fi
if [ ! -d "repos/V75_TinyCrypt_tests" ]; then git clone --depth 1 https://github.com/intel/tinycrypt repos/V75_TinyCrypt_tests/; else echo "SKIP V75 exists"; fi
if [ ! -d "repos/V76_NIST_LWC_KAT_vectors" ]; then git clone --depth 1 https://csrc.nist.gov/Projects/lightweight-cryptography/finalists repos/V76_NIST_LWC_KAT_vectors/; else echo "SKIP V76 exists"; fi
if [ ! -d "repos/V77_CAESAR_KAT_archive" ]; then git clone --depth 1 https://competitions.cr.yp.to/caesar-submissions.html repos/V77_CAESAR_KAT_archive/; else echo "SKIP V77 exists"; fi
if [ ! -d "repos/V78_SUPERCOP_Benchmark_data" ]; then git clone --depth 1 https://bench.cr.yp.to/supercop.html repos/V78_SUPERCOP_Benchmark_data/; else echo "SKIP V78 exists"; fi
if [ ! -d "repos/V79_eSTREAM_KAT_archive" ]; then git clone --depth 1 https://www.ecrypt.eu.org/stream/ repos/V79_eSTREAM_KAT_archive/; else echo "SKIP V79 exists"; fi
if [ ! -d "repos/V80_NIST_CAVS_Test_Vectors" ]; then git clone --depth 1 https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program repos/V80_NIST_CAVS_Test_Vectors/; else echo "SKIP V80 exists"; fi
if [ ! -d "repos/V81_NIST_PQC_KATs_Round_4" ]; then git clone --depth 1 https://csrc.nist.gov/projects/post-quantum-cryptography/post-quantum-cryptography-standardization/round-4-submissions repos/V81_NIST_PQC_KATs_Round_4/; else echo "SKIP V81 exists"; fi
if [ ! -d "repos/V82_TinyJAMBU_test_vectors" ]; then git clone --depth 1 https://github.com/rweather/TinyJAMBU repos/V82_TinyJAMBU_test_vectors/; else echo "SKIP V82 exists"; fi
if [ ! -d "repos/V83_Romulus_KAT" ]; then git clone --depth 1 https://github.com/romulusae/romulus repos/V83_Romulus_KAT/; else echo "SKIP V83 exists"; fi
if [ ! -d "repos/V84_Ascon_test_vectors" ]; then git clone --depth 1 https://github.com/ascon/ascon-c repos/V84_Ascon_test_vectors/; else echo "SKIP V84 exists"; fi
if [ ! -d "repos/V85_LWC_Finalists_Test_Data" ]; then git clone --depth 1 https://github.com/rweather/lwc-finalists repos/V85_LWC_Finalists_Test_Data/; else echo "SKIP V85 exists"; fi
if [ ! -d "repos/V86_SPHINCS__KAT" ]; then git clone --depth 1 https://github.com/sphincs/sphincsplus repos/V86_SPHINCS__KAT/; else echo "SKIP V86 exists"; fi
if [ ! -d "repos/V87_Classic_McEliece_KAT" ]; then git clone --depth 1 https://github.com/PQClean/PQClean repos/V87_Classic_McEliece_KAT/; else echo "SKIP V87 exists"; fi
if [ ! -d "repos/V88_Kyber_ML-KEM_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/kyber repos/V88_Kyber_ML-KEM_KAT/; else echo "SKIP V88 exists"; fi
if [ ! -d "repos/V89_Dilithium_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/dilithium repos/V89_Dilithium_KAT/; else echo "SKIP V89 exists"; fi
if [ ! -d "repos/V90_Falcon_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/falcon repos/V90_Falcon_KAT/; else echo "SKIP V90 exists"; fi
if [ ! -d "repos/V91_NTRU_Prime_KAT" ]; then git clone --depth 1 https://github.com/ntruprime/ntruprime repos/V91_NTRU_Prime_KAT/; else echo "SKIP V91 exists"; fi
if [ ! -d "repos/V92_getrandom_tests" ]; then git clone --depth 1 https://github.com/openbsd/src repos/V92_getrandom_tests/; else echo "SKIP V92 exists"; fi
if [ ! -d "repos/V93_GRUB_Linux_getrandom" ]; then git clone --depth 1 https://github.com/torvalds/linux repos/V93_GRUB_Linux_getrandom/; else echo "SKIP V93 exists"; fi
if [ ! -d "repos/V94_EAGLE_RNG_tests" ]; then git clone --depth 1 https://github.com/linux/hw_random repos/V94_EAGLE_RNG_tests/; else echo "SKIP V94 exists"; fi
if [ ! -d "repos/V95_Haveged_tests" ]; then git clone --depth 1 https://github.com/jirka-h/haveged repos/V95_Haveged_tests/; else echo "SKIP V95 exists"; fi
if [ ! -d "repos/V96_Jitter_tests" ]; then git clone --depth 1 https://github.com/smuellerDD/jitterentropy-library repos/V96_Jitter_tests/; else echo "SKIP V96 exists"; fi
if [ ! -d "repos/V97_Lavarand_tests" ]; then git clone --depth 1 https://github.com/lavarand repos/V97_Lavarand_tests/; else echo "SKIP V97 exists"; fi
if [ ! -d "repos/V98_NIST_Beacon_tests" ]; then git clone --depth 1 https://github.com/usnistgov/RandomnessBeacon repos/V98_NIST_Beacon_tests/; else echo "SKIP V98 exists"; fi
if [ ! -d "repos/V99_opencryptoki_tests" ]; then git clone --depth 1 https://github.com/opencryptoki/opencryptoki repos/V99_opencryptoki_tests/; else echo "SKIP V99 exists"; fi
if [ ! -d "repos/V100_OpenSSL_FIPS_test_vectors" ]; then git clone --depth 1 https://github.com/openssl/openssl repos/V100_OpenSSL_FIPS_test_vectors/; else echo "SKIP V100 exists"; fi
if [ ! -d "repos/V101_wolfSSL_FIPS_validation" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfssl repos/V101_wolfSSL_FIPS_validation/; else echo "SKIP V101 exists"; fi
if [ ! -d "repos/V102_Linux_RNG_tests" ]; then git clone --depth 1 https://github.com/torvalds/linux repos/V102_Linux_RNG_tests/; else echo "SKIP V102 exists"; fi
if [ ! -d "repos/V103_Windows_CNG_test_vectors" ]; then git clone --depth 1 https://docs.microsoft.com/windows/win32/seccng/test-vectors repos/V103_Windows_CNG_test_vectors/; else echo "SKIP V103 exists"; fi
if [ ! -d "repos/V105_Crypto___tests" ]; then git clone --depth 1 https://github.com/weidai11/cryptopp repos/V105_Crypto___tests/; else echo "SKIP V105 exists"; fi
if [ ! -d "repos/V106_eSTREAM_KAT" ]; then git clone --depth 1 http://www.ecrypt.eu.org/stream/ repos/V106_eSTREAM_KAT/; else echo "SKIP V106 exists"; fi
if [ ! -d "repos/V107_Botan_X.509_tests" ]; then git clone --depth 1 https://github.com/randombit/botan/tree/master/src/tests repos/V107_Botan_X.509_tests/; else echo "SKIP V107 exists"; fi
if [ ! -d "repos/V108_OpenSSL_test_suite" ]; then git clone --depth 1 https://github.com/openssl/openssl/tree/master/test repos/V108_OpenSSL_test_suite/; else echo "SKIP V108 exists"; fi
if [ ! -d "repos/V109_wolfSSL_test" ]; then git clone --depth 1 https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/test repos/V109_wolfSSL_test/; else echo "SKIP V109 exists"; fi
if [ ! -d "repos/V110_CFSSL_tests" ]; then git clone --depth 1 https://github.com/cloudflare/cfssl repos/V110_CFSSL_tests/; else echo "SKIP V110 exists"; fi
if [ ! -d "repos/V111_libsnark_tests" ]; then git clone --depth 1 https://github.com/scipr-lab/libsnark repos/V111_libsnark_tests/; else echo "SKIP V111 exists"; fi
if [ ! -d "repos/V112_arkworks_tests" ]; then git clone --depth 1 https://github.com/arkworks-rs repos/V112_arkworks_tests/; else echo "SKIP V112 exists"; fi
if [ ! -d "repos/V113_MIRACL_Core_tests" ]; then git clone --depth 1 https://github.com/miracl/core repos/V113_MIRACL_Core_tests/; else echo "SKIP V113 exists"; fi
if [ ! -d "repos/V114_RELIC_tests" ]; then git clone --depth 1 https://github.com/relic-toolkit/relic/tree/master/test repos/V114_RELIC_tests/; else echo "SKIP V114 exists"; fi
if [ ! -d "repos/V115_OpenBSD_crypto_tests" ]; then git clone --depth 1 https://github.com/openbsd/src repos/V115_OpenBSD_crypto_tests/; else echo "SKIP V115 exists"; fi
if [ ! -d "repos/V116_libsodium_tests" ]; then git clone --depth 1 https://github.com/jedisct1/libsodium/tree/master/test/default repos/V116_libsodium_tests/; else echo "SKIP V116 exists"; fi
if [ ! -d "repos/V117_Monocypher_tests" ]; then git clone --depth 1 https://github.com/LoupVaillant/Monocypher/tree/master/tests repos/V117_Monocypher_tests/; else echo "SKIP V117 exists"; fi
if [ ! -d "repos/V118_TinyCrypt_tests" ]; then git clone --depth 1 https://github.com/intel/tinycrypt/tree/master/tests repos/V118_TinyCrypt_tests/; else echo "SKIP V118 exists"; fi
if [ ! -d "repos/V119_Mbed_TLS_tests" ]; then git clone --depth 1 https://github.com/Mbed-TLS/mbedtls/tree/master/tests repos/V119_Mbed_TLS_tests/; else echo "SKIP V119 exists"; fi
if [ ! -d "repos/V120_libhydrogen_tests" ]; then git clone --depth 1 https://github.com/jedisct1/libhydrogen/tree/master/tests repos/V120_libhydrogen_tests/; else echo "SKIP V120 exists"; fi
if [ ! -d "repos/V121_BearSSL_tests" ]; then git clone --depth 1 https://bearssl.org repos/V121_BearSSL_tests/; else echo "SKIP V121 exists"; fi
if [ ! -d "repos/V122_BoringSSL_tests" ]; then git clone --depth 1 https://github.com/google/boringssl/tree/master/ssl/test repos/V122_BoringSSL_tests/; else echo "SKIP V122 exists"; fi
if [ ! -d "repos/V123_AWS-LC_tests" ]; then git clone --depth 1 https://github.com/aws/aws-lc/tree/main/tests repos/V123_AWS-LC_tests/; else echo "SKIP V123 exists"; fi
if [ ! -d "repos/V124_PQClean_tests" ]; then git clone --depth 1 https://github.com/PQClean/PQClean/tree/master/test repos/V124_PQClean_tests/; else echo "SKIP V124 exists"; fi
if [ ! -d "repos/V125_SPHINCS__KAT" ]; then git clone --depth 1 https://github.com/sphincs/sphincsplus repos/V125_SPHINCS__KAT/; else echo "SKIP V125 exists"; fi
if [ ! -d "repos/V126_NTRU_Prime_KAT" ]; then git clone --depth 1 https://github.com/ntruprime/ntruprime repos/V126_NTRU_Prime_KAT/; else echo "SKIP V126 exists"; fi
if [ ! -d "repos/V127_Kyber_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/kyber repos/V127_Kyber_KAT/; else echo "SKIP V127 exists"; fi
if [ ! -d "repos/V128_Dilithium_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/dilithium repos/V128_Dilithium_KAT/; else echo "SKIP V128 exists"; fi
if [ ! -d "repos/V129_Falcon_KAT" ]; then git clone --depth 1 https://github.com/pq-crystals/falcon repos/V129_Falcon_KAT/; else echo "SKIP V129 exists"; fi
if [ ! -d "repos/V130_Signal_Protocol_tests" ]; then git clone --depth 1 https://github.com/signalapp/libsignal repos/V130_Signal_Protocol_tests/; else echo "SKIP V130 exists"; fi
if [ ! -d "repos/V131_OpenSSH_tests" ]; then git clone --depth 1 https://github.com/openssh/openssh-portable/tree/master/regress repos/V131_OpenSSH_tests/; else echo "SKIP V131 exists"; fi
if [ ! -d "repos/V132_OpenSSH_KAT" ]; then git clone --depth 1 https://github.com/openssh/openssh-portable repos/V132_OpenSSH_KAT/; else echo "SKIP V132 exists"; fi

echo "[DONE] All repository cloning attempted."