"""
script/core/load.py
───────────────────
Test-load distribution maps.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Map structure
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MAP[tier][module_path] = [test_key, ...]

module_path mirrors the real file path inside script/test/, without .py:
    'partial/pqc/kem_lattice'   → script/test/partial/pqc/kem_lattice.py
    'base/pqc_kem_main'         → script/test/base/pqc_kem_main.py
    'main/pqc'                  → script/test/main/pqc.py
    'primary/system'            → script/test/primary/system.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Key naming convention
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{group}_headers     symbol / class availability check for the group's DLL.
                    Runner confirms every exported symbol and struct header
                    is accessible before executing any functional test.

{algo}              core functional test  (keygen / encrypt / sign / verify)
{algo}_drbg         DRBG determinism      (same seed  → identical output)
{algo}_udbf         UDBF determinism      (same buffer → identical output)
{algo}_derand       derand API            (keypair_derand / encaps_derand / sign_derand)
pow_{algo}_d{n}     PoW challenge/solve at difficulty n bits

Hash, Cipher, MAC, ECC, DHCM — no _drbg/_udbf/_derand (no keypair RNG)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Header rule  (enforced by _h helper below)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EVERY non-empty module list starts with {group}_headers.
This fires in ALL maps, including LOAD_MAP_QUICK.

In LOAD_MAP / LOAD_MAP_ALL:
    []              → build-only; runner skips tests entirely, logs "[LOAD] build only"
    _h('grp', ...)  → header check first, then functional tests

In LOAD_MAP_QUICK:
    _h('grp')       → header-only; no functional tests (confirms DLL is loadable)
    _h('grp', ...)  → header check then those specific tests

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Checksums / manifest
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
bin/{platform}/checksums.json
    Generated by script/gen/checksums.py after each build.
    Contains SHA-256 of every compiled binary — NO timestamps, NO build IDs.
    Identical source → identical binaries → identical checksums (always).
    CI uploads this file as a release artifact for download verification.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Three maps  (activated by runner flag / CI input)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
LOAD_MAP        --gen       Default: well-distributed, heavy algos deferred
LOAD_MAP_ALL    --genAll    Every algo tested, spread across tiers (no dups)
LOAD_MAP_QUICK  --genQuick  Header check per module + selective smoke tests

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Main-tier declared test sets (used in LOAD_MAP / LOAD_MAP_ALL respectively)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MAIN_DEFAULT_TESTS — optimised essentials  (used by LOAD_MAP)
MAIN_SUPER_TESTS   — every key; devs extend this list  (standalone reference)
"""

# ─────────────────────────────────────────────────────────────────────────────
# §1  MASTER ALGORITHM LISTS  (single source of truth)
# ─────────────────────────────────────────────────────────────────────────────

# ── PQC: KEM ──────────────────────────────────────────────────────────────────
_MLKEM      = ['mlkem512', 'mlkem768', 'mlkem1024']
_HQC        = ['hqc128', 'hqc192', 'hqc256']
_MCELIECE_S = ['mceliece348864',  'mceliece348864f',
            'mceliece460896',  'mceliece460896f']          # small → base
_MCELIECE_L = ['mceliece6688128', 'mceliece6688128f',
            'mceliece6960119', 'mceliece6960119f',
            'mceliece8192128', 'mceliece8192128f']         # large → main
_MCELIECE   = _MCELIECE_S + _MCELIECE_L

# ── PQC: Signature ────────────────────────────────────────────────────────────
_MLDSA      = ['mldsa44', 'mldsa65', 'mldsa87']
_FALCON     = ['falcon512', 'falcon1024', 'falcon_padded512', 'falcon_padded1024']
_SPHINCS_F  = [                                                # fast variants
    'sphincs_sha2_128f',  'sphincs_sha2_192f',  'sphincs_sha2_256f',
    'sphincs_shake_128f', 'sphincs_shake_192f', 'sphincs_shake_256f',
]
_SPHINCS_S  = [                                                # slow variants
    'sphincs_sha2_128s',  'sphincs_sha2_192s',  'sphincs_sha2_256s',
    'sphincs_shake_128s', 'sphincs_shake_192s', 'sphincs_shake_256s',
]
_SPHINCS    = _SPHINCS_F + _SPHINCS_S

# ── Hash ──────────────────────────────────────────────────────────────────────
_H_FAST     = ['sha256', 'sha512', 'blake3', 'blake2b', 'blake2s', 'sha224', 'sha384']
_H_MEM      = ['argon2id', 'argon2i', 'argon2d']
_H_SPONGE   = ['sha3_256', 'sha3_512', 'keccak256', 'shake128', 'shake256']
_H_L_ALIVE  = ['md5', 'sha1', 'ripemd160']
_H_L_UNSAFE = ['md2', 'md4', 'sha0', 'has160', 'ripemd128', 'ripemd256', 'ripemd320']

# ── Core ──────────────────────────────────────────────────────────────────────
_C_MODES    = ['aes_cbc', 'aes_xts']
_C_AEAD_AES = ['aes_gcm']
_C_AEAD_STR = ['chacha20_poly1305']
_C_MAC      = ['aes_cmac', 'hmac_sha256']
_C_ECC      = ['ed25519', 'x25519']

# ── DHCM (prefix from Hash) ───────────────────────────────────────────────────
_D_FAST     = [f'dhcm_{h}' for h in _H_FAST]
_D_MEM      = [f'dhcm_{h}' for h in _H_MEM]
_D_SPONGE   = [f'dhcm_{h}' for h in _H_SPONGE]
_D_L_ALIVE  = [f'dhcm_{h}' for h in _H_L_ALIVE]
_D_L_UNSAFE = [f'dhcm_{h}' for h in ['md2', 'md4', 'sha0', 'has160']]

# ── PoW base names (prefix from Hash) ────────────────────────────────────────
_P_FAST     = [f'pow_{h}' for h in _H_FAST]
_P_MEM      = [f'pow_{h}' for h in _H_MEM]
_P_SPONGE   = [f'pow_{h}' for h in _H_SPONGE]
_P_L_ALIVE  = [f'pow_{h}' for h in _H_L_ALIVE]
_P_L_UNSAFE = [f'pow_{h}' for h in ['md2', 'md4', 'sha0']]
_PC_FAST    = [f'pow_combined_{h}' for h in _H_FAST]
_PC_MEM     = [f'pow_combined_{h}' for h in _H_MEM]
_PC_SPONGE  = [f'pow_combined_{h}' for h in _H_SPONGE]

# ─────────────────────────────────────────────────────────────────────────────
# §2  HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _h(group, *keys):
    """Prepend {group}_headers to the test list.
    EVERY non-empty module entry must use this — enforces the header-first rule.

    _h('hash')              → ['hash_headers']               (header-only)
    _h('hash', 'sha256')    → ['hash_headers', 'sha256']
    _h('pqc', *_v(_MLKEM))  → ['pqc_headers', 'mlkem512', 'mlkem768', 'mlkem1024']
    """
    return [f'{group}_headers'] + list(keys)

def _v(algos, *suffixes):
    """Expand algo names with each suffix.
    _v(_MLKEM)               → ['mlkem512', 'mlkem768', 'mlkem1024']
    _v(_MLKEM, '', '_drbg')  → ['mlkem512', 'mlkem512_drbg', 'mlkem768', ...]
    """
    if not suffixes:
        suffixes = ('',)
    return [a + s for a in algos for s in suffixes]

def _d(bases, *difficulties):
    """Append _d{n} difficulty suffixes.
    _d(_P_FAST, 1, 4) → ['pow_sha256_d1', 'pow_sha256_d4', ...]
    """
    return [f'{b}_d{d}' for b in bases for d in difficulties]

# All 4 PQC test-type suffixes
_ALL4 = ('', '_drbg', '_udbf', '_derand')

# ─────────────────────────────────────────────────────────────────────────────
# §3  PRIMARY_ALWAYS
#     Mini integration test always appended to primary/system and
#     primary/system_lite regardless of the active map.
#     Contract: must complete in ≤ 4 min on any supported platform.
#     Built from master lists — auto-updates when lists change.
# ─────────────────────────────────────────────────────────────────────────────
PRIMARY_ALWAYS = {
    # Full system DLL: one algo per family + profiling ping + smoke
    'primary/system': _h('system',
        'system_profile',       # profiling ping (always first)
        _H_FAST[0],             # sha256
        _H_MEM[0],              # argon2id
        _H_SPONGE[0],           # sha3_256
        _H_L_ALIVE[0],          # md5
        _C_AEAD_AES[0],         # aes_gcm
        _C_AEAD_STR[0],         # chacha20_poly1305
        _C_ECC[0],              # ed25519
        _D_FAST[0],             # dhcm_sha256
        _d(_P_FAST[:1], 1)[0],  # pow_sha256_d1
        _MLKEM[0],              # mlkem512
        _MLDSA[0],              # mldsa44
        'system_main',          # final integrated smoke
    ),
    # Lite system DLL: lighter set + lite smoke
    'primary/system_lite': _h('system',
        'system_profile_lite',  # profiling ping
        _H_FAST[0],             # sha256
        _C_AEAD_AES[0],         # aes_gcm
        _C_ECC[0],              # ed25519
        _MLKEM[0],              # mlkem512
        'system_lite',          # unified DLL smoke
    ),
}

# ─────────────────────────────────────────────────────────────────────────────
# §4  MAIN-TIER DECLARED TEST SETS
# ─────────────────────────────────────────────────────────────────────────────

# Used by LOAD_MAP — essentials, well-distributed, fast main tier
MAIN_DEFAULT_TESTS = {
    'main/hash': _h('hash', 'hash_main'),
    'main/core': _h('core', 'core_main'),
    'main/dhcm': _h('dhcm', 'dhcm_main'),
    'main/pow': _h('pow',
        *_d(_PC_FAST[:3],   4),   # combined sha256/sha512/blake3 d4
        *_d(_PC_SPONGE[:2], 4),   # combined sha3_256/sha3_512 d4
        *_d(_PC_MEM[:1], 1, 4),   # combined argon2id d1+d4
        'pow_main',
    ),
    'main/pow_combined': _h('pow', 'pow_combined_main'),
    # McEliece large — core only in default
    # SPHINCS+ fast  — core + DRBG only in default
    'main/pqc': _h('pqc',
        *_v(_MCELIECE_L, ''),
        *_v(_SPHINCS_F, '', '_drbg'),
        'pqc_sign_main',
        'pqc_main',
    ),
}

# Used by devs and LOAD_MAP_ALL main tier — full standalone main-tier suite.
# Add new test keys to the appropriate inner list here.
MAIN_SUPER_TESTS = {
    'main/hash': _h('hash',
        'hash_main',
        *_H_FAST, *_H_MEM, *_H_SPONGE, *_H_L_ALIVE, *_H_L_UNSAFE,
    ),
    'main/core': _h('core',
        'core_main',
        *_C_MODES, *_C_AEAD_AES, *_C_AEAD_STR, *_C_MAC, *_C_ECC,
    ),
    'main/dhcm': _h('dhcm',
        'dhcm_main',
        *_D_FAST, *_D_MEM, *_D_SPONGE, *_D_L_ALIVE, *_D_L_UNSAFE,
    ),
    'main/pow': _h('pow',
        *_d(_P_FAST,    1, 4),
        *_d(_P_SPONGE,  1, 4),
        *_d(_P_MEM,     1, 4),
        *_d(_PC_FAST,   1, 4),
        *_d(_PC_SPONGE, 1, 4),
        *_d(_PC_MEM,    1, 4),
        'pow_main',
    ),
    'main/pow_combined': _h('pow', 'pow_combined_main'),
    # NOTE: PQC in MAIN_SUPER_TESTS covers ALL variants (including those
    # already tested in partial/base).  Use as standalone isolation run,
    # NOT embedded in LOAD_MAP_ALL (which only adds what partial/base didn't).
    'main/pqc': _h('pqc',
        *_v(_MLKEM,          *_ALL4),
        *_v(_HQC,            *_ALL4),
        *_v(_MCELIECE,       *_ALL4),
        *_v(_MLDSA + _FALCON, *_ALL4),
        *_v(_SPHINCS,        *_ALL4),
        'pqc_sign_main',
        'pqc_main',
    ),
}

# ─────────────────────────────────────────────────────────────────────────────
# §5  LOAD_MAP — Default / Well-Distributed  (--gen)
# ─────────────────────────────────────────────────────────────────────────────
LOAD_MAP = {

    # ── partial ───────────────────────────────────────────────────────────────
    'partial': {
        # Hash unit tests
        'partial/hash/primitive_fast':        _h('hash', *_H_FAST),
        'partial/hash/primitive_memory_hard': _h('hash', *_H_MEM),
        'partial/hash/primitive_sponge_xof':  _h('hash', *_H_SPONGE),
        'partial/hash/legacy_alive':          _h('hash', *_H_L_ALIVE),
        'partial/hash/legacy_unsafe':         _h('hash', *_H_L_UNSAFE),

        # Core unit tests
        'partial/core/aes_modes':             _h('core', *_C_MODES),
        'partial/core/aes_aead':              _h('core', *_C_AEAD_AES),
        'partial/core/stream_aead':           _h('core', *_C_AEAD_STR),
        'partial/core/macs':                  _h('core', *_C_MAC),
        'partial/core/ecc':                   _h('core', *_C_ECC),

        # DHCM unit tests
        'partial/dhcm/primitive_fast':        _h('dhcm', *_D_FAST),
        'partial/dhcm/primitive_memory_hard': _h('dhcm', *_D_MEM),
        'partial/dhcm/primitive_sponge_xof':  _h('dhcm', *_D_SPONGE),
        'partial/dhcm/legacy_alive':          _h('dhcm', *_D_L_ALIVE),
        'partial/dhcm/legacy_unsafe':         _h('dhcm', *_D_L_UNSAFE),

        # PoW d1 only in partial; d4 deferred to base
        'partial/pow/primitive_fast':         _h('pow', *_d(_P_FAST,   1)),
        'partial/pow/primitive_memory_hard':  _h('pow', *_d(_P_MEM,    1)),
        'partial/pow/primitive_sponge_xof':   _h('pow', *_d(_P_SPONGE, 1)),
        'partial/pow/legacy_alive':           _h('pow', *_d(_P_L_ALIVE,  1)),
        'partial/pow/legacy_unsafe':          _h('pow', *_d(_P_L_UNSAFE, 1)),

        # PQC lattice — all 4 test types; HQC / McEliece / SPHINCS+ deferred
        'partial/pqc/kem_lattice':            _h('pqc', *_v(_MLKEM,           *_ALL4)),
        'partial/pqc/sign_lattice':           _h('pqc', *_v(_MLDSA + _FALCON, *_ALL4)),
    },

    # ── base ──────────────────────────────────────────────────────────────────
    'base': {
        # Integration smoke tests
        'base/hash_primitive_main': _h('hash', 'hash_primitive_main'),
        'base/hash_legacy_main':    _h('hash', 'hash_legacy_main'),
        'base/core_cipher_main':    _h('core', 'core_cipher_main'),
        'base/core_mac_main':       _h('core', 'core_mac_main'),
        'base/core_ecc_main':       _h('core', 'core_ecc_main'),
        'base/dhcm_primitive_main': _h('dhcm', 'dhcm_primitive_main'),
        'base/dhcm_legacy_main':    _h('dhcm', 'dhcm_legacy_main'),

        # PoW d4 + combined d1  (individual d1 already in partial above)
        'base/pow_primitive': _h('pow',
            *_d(_P_FAST,   4),
            *_d(_P_SPONGE, 4),
            *_d(_P_MEM,    4),
        ),
        'base/pow_combined': _h('pow',
            *_d(_PC_FAST[:3],   1),   # sha256, sha512, blake3 d1
            *_d(_PC_SPONGE[:2], 1),   # sha3_256, sha3_512 d1
        ),

        # HQC all 4 test types; McEliece small core+DRBG only in default
        'base/pqc_kem_main': _h('pqc',
            *_v(_HQC,        *_ALL4),
            *_v(_MCELIECE_S, '', '_drbg'),
            'pqc_kem_main',
        ),
    },

    'main': MAIN_DEFAULT_TESTS,

    # ── primary ───────────────────────────────────────────────────────────────
    # PRIMARY_ALWAYS is always injected by the runner regardless of map.
    # Entries here are [] = build-only stubs; PRIMARY_ALWAYS fills the real tests.
    'primary': {
        'primary/system':      [],
        'primary/system_lite': [],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# §6  LOAD_MAP_ALL — Every algo, every variant, spread across tiers  (--genAll)
#
#   Nothing is duplicated — each key appears exactly once across partial+base+main.
#   Spread logic for PQC:
#     partial  → lattice core+DRBG; HQC core; SPHINCS_F core
#     base     → lattice UDBF+derand; HQC DRBG+UDBF+derand; McEliece small full
#                SPHINCS_S core (slow variants)
#     main     → McEliece large full 4-way; SPHINCS all DRBG+UDBF+derand
# ─────────────────────────────────────────────────────────────────────────────
LOAD_MAP_ALL = {

    # ── partial ───────────────────────────────────────────────────────────────
    'partial': {
        # Hash / Core / DHCM — same as LOAD_MAP (atomic full lists)
        'partial/hash/primitive_fast':        _h('hash', *_H_FAST),
        'partial/hash/primitive_memory_hard': _h('hash', *_H_MEM),
        'partial/hash/primitive_sponge_xof':  _h('hash', *_H_SPONGE),
        'partial/hash/legacy_alive':          _h('hash', *_H_L_ALIVE),
        'partial/hash/legacy_unsafe':         _h('hash', *_H_L_UNSAFE),

        'partial/core/aes_modes':             _h('core', *_C_MODES),
        'partial/core/aes_aead':              _h('core', *_C_AEAD_AES),
        'partial/core/stream_aead':           _h('core', *_C_AEAD_STR),
        'partial/core/macs':                  _h('core', *_C_MAC),
        'partial/core/ecc':                   _h('core', *_C_ECC),

        'partial/dhcm/primitive_fast':        _h('dhcm', *_D_FAST),
        'partial/dhcm/primitive_memory_hard': _h('dhcm', *_D_MEM),
        'partial/dhcm/primitive_sponge_xof':  _h('dhcm', *_D_SPONGE),
        'partial/dhcm/legacy_alive':          _h('dhcm', *_D_L_ALIVE),
        'partial/dhcm/legacy_unsafe':         _h('dhcm', *_D_L_UNSAFE),

        # PoW d1 only (d4 in base)
        'partial/pow/primitive_fast':         _h('pow', *_d(_P_FAST,   1)),
        'partial/pow/primitive_memory_hard':  _h('pow', *_d(_P_MEM,    1)),
        'partial/pow/primitive_sponge_xof':   _h('pow', *_d(_P_SPONGE, 1)),
        'partial/pow/legacy_alive':           _h('pow', *_d(_P_L_ALIVE,  1)),
        'partial/pow/legacy_unsafe':          _h('pow', *_d(_P_L_UNSAFE, 1)),

        # PQC lattice core+DRBG only (UDBF/derand → base)
        # HQC core only (rest → base)
        # SPHINCS_F core only (rest → base/main)
        'partial/pqc/kem_lattice':            _h('pqc', *_v(_MLKEM,           '', '_drbg')),
        'partial/pqc/kem_code_based':         _h('pqc', *_v(_HQC,             '')),
        'partial/pqc/sign_lattice':           _h('pqc', *_v(_MLDSA + _FALCON, '', '_drbg')),
        'partial/pqc/sign_hash_based':        _h('pqc', *_v(_SPHINCS_F,       '')),
    },

    # ── base ──────────────────────────────────────────────────────────────────
    'base': {
        'base/hash_primitive_main': _h('hash', 'hash_primitive_main'),
        'base/hash_legacy_main':    _h('hash', 'hash_legacy_main'),
        'base/core_cipher_main':    _h('core', 'core_cipher_main'),
        'base/core_mac_main':       _h('core', 'core_mac_main'),
        'base/core_ecc_main':       _h('core', 'core_ecc_main'),
        'base/dhcm_primitive_main': _h('dhcm', 'dhcm_primitive_main'),
        'base/dhcm_legacy_main':    _h('dhcm', 'dhcm_legacy_main'),

        # PoW d4 + combined d1+d4  (individual d1 already in partial)
        'base/pow_primitive': _h('pow',
            *_d(_P_FAST,   4),
            *_d(_P_SPONGE, 4),
            *_d(_P_MEM,    4),
        ),
        'base/pow_combined': _h('pow',
            *_d(_PC_FAST,   1, 4),
            *_d(_PC_SPONGE, 1, 4),
            *_d(_PC_MEM,    1),     # argon2 combined d1 only; d4 → main
        ),

        # Lattice UDBF+derand (core+DRBG were in partial)
        # HQC DRBG+UDBF+derand (core was in partial)
        # McEliece small full 4-way
        # SPHINCS_S core only (slow, deferred from partial)
        'base/pqc_kem_main': _h('pqc',
            *_v(_MLKEM,        '_udbf', '_derand'),
            *_v(_HQC,          '_drbg', '_udbf', '_derand'),
            *_v(_MCELIECE_S,   *_ALL4),
            'pqc_kem_main',
        ),
        'base/pqc_sign_main': _h('pqc',
            *_v(_MLDSA + _FALCON, '_udbf', '_derand'),
            *_v(_SPHINCS_S,       ''),    # core only (drbg/udbf/derand → main)
            # pqc_sign_main deferred to main/pqc to avoid dup
        ),
    },

    # ── main ──────────────────────────────────────────────────────────────────
    # Only what partial/base didn't cover:
    #   McEliece large full 4-way
    #   SPHINCS_F DRBG+UDBF+derand (core was in partial)
    #   SPHINCS_S DRBG+UDBF+derand (core was in base)
    #   argon2 combined d4 (d1 was in base)
    'main': {
        'main/hash': _h('hash', 'hash_main'),
        'main/core': _h('core', 'core_main'),
        'main/dhcm': _h('dhcm', 'dhcm_main'),
        'main/pow': _h('pow',
            *_d(_PC_MEM, 4),        # argon2 combined d4 only (d1 was in base)
            'pow_main',
        ),
        'main/pow_combined': _h('pow', 'pow_combined_main'),
        'main/pqc': _h('pqc',
            *_v(_MCELIECE_L,       *_ALL4),
            *_v(_SPHINCS_F,        '_drbg', '_udbf', '_derand'),
            *_v(_SPHINCS_S,        '_drbg', '_udbf', '_derand'),
            'pqc_sign_main',
            'pqc_main',
        ),
    },

    'primary': {
        'primary/system':      [],
        'primary/system_lite': [],
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# §7  LOAD_MAP_QUICK — Header check + selective smoke  (--genQuick)
#
#   Runner behaviour:
#     1. For every module: _h(group) = {group}_headers fires first (always)
#     2. _h(group)        → header-only, no functional tests
#     3. _h(group, ...)   → header check then those tests
#     4. []               → build-only (runner skips entirely, no header check)
#     5. PRIMARY_ALWAYS fires for primary tier regardless
#
#   Target: entire run completes in < 5 min on any platform.
# ─────────────────────────────────────────────────────────────────────────────
LOAD_MAP_QUICK = {

    'partial': {
        # One algo per hash module — confirms module loads + one path works
        'partial/hash/primitive_fast':        _h('hash', _H_FAST[0]),        # sha256
        'partial/hash/primitive_memory_hard': _h('hash', _H_MEM[0]),         # argon2id
        'partial/hash/primitive_sponge_xof':  _h('hash', _H_SPONGE[0]),      # sha3_256
        'partial/hash/legacy_alive':          _h('hash', _H_L_ALIVE[0]),     # md5
        'partial/hash/legacy_unsafe':         _h('hash'),                    # header-only

        'partial/core/aes_modes':             _h('core', _C_MODES[0]),       # aes_cbc
        'partial/core/aes_aead':              _h('core', *_C_AEAD_AES),      # aes_gcm
        'partial/core/stream_aead':           _h('core', *_C_AEAD_STR),      # chacha20_poly1305
        'partial/core/macs':                  _h('core', _C_MAC[1]),         # hmac_sha256
        'partial/core/ecc':                   _h('core', _C_ECC[0]),         # ed25519

        'partial/dhcm/primitive_fast':        _h('dhcm', _D_FAST[0]),        # dhcm_sha256
        'partial/dhcm/primitive_memory_hard': _h('dhcm', _D_MEM[0]),         # dhcm_argon2id
        'partial/dhcm/primitive_sponge_xof':  _h('dhcm', _D_SPONGE[0]),      # dhcm_sha3_256
        'partial/dhcm/legacy_alive':          _h('dhcm', _D_L_ALIVE[0]),     # dhcm_md5
        'partial/dhcm/legacy_unsafe':         _h('dhcm'),                    # header-only

        'partial/pow/primitive_fast':         _h('pow', _d(_P_FAST[:1],   1)[0]),  # pow_sha256_d1
        'partial/pow/primitive_memory_hard':  _h('pow'),                     # header-only (slow)
        'partial/pow/primitive_sponge_xof':   _h('pow', _d(_P_SPONGE[:1], 1)[0]), # pow_sha3_256_d1
        'partial/pow/legacy_alive':           _h('pow', _d(_P_L_ALIVE[:1], 1)[0]), # pow_md5_d1
        'partial/pow/legacy_unsafe':          _h('pow'),                     # header-only

        'partial/pqc/kem_lattice':            _h('pqc', _MLKEM[0]),          # mlkem512
        'partial/pqc/kem_code_based':         _h('pqc'),                     # header-only (slow)
        'partial/pqc/sign_lattice':           _h('pqc', _MLDSA[0]),          # mldsa44
        'partial/pqc/sign_hash_based':        _h('pqc'),                     # header-only (slow)
    },

    'base': {
        'base/hash_primitive_main': _h('hash', 'hash_primitive_main'),
        'base/hash_legacy_main':    _h('hash'),                              # header-only
        'base/core_cipher_main':    _h('core', 'core_cipher_main'),
        'base/core_mac_main':       _h('core'),                              # header-only
        'base/core_ecc_main':       _h('core', 'core_ecc_main'),
        'base/dhcm_primitive_main': _h('dhcm', 'dhcm_primitive_main'),
        'base/dhcm_legacy_main':    _h('dhcm'),                              # header-only
        'base/pow_primitive':       _h('pow',  _d(_P_FAST[:1], 4)[0]),       # pow_sha256_d4
        'base/pow_combined':        _h('pow',  _d(_PC_FAST[:1], 1)[0]),      # pow_combined_sha256_d1
        'base/pqc_kem_main':        _h('pqc',  _HQC[0]),                     # hqc128 core only
        'base/pqc_sign_main':       _h('pqc'),                               # header-only
    },

    'main': {
        'main/hash':         _h('hash', 'hash_main'),
        'main/core':         _h('core', 'core_main'),
        'main/dhcm':         _h('dhcm', 'dhcm_main'),
        'main/pow':          _h('pow',  'pow_main'),
        'main/pow_combined': _h('pow'),                                      # header-only
        'main/pqc':          _h('pqc',  _SPHINCS_F[0], 'pqc_main'),          # sphincs_sha2_128f
    },

    'primary': {
        'primary/system':      [],   # PRIMARY_ALWAYS handles this
        'primary/system_lite': [],   # PRIMARY_ALWAYS handles this
    },
}
